### ISSUE TITLE
Incluir slides como links

### ISSUE THREAD

**Issue by msoltadeo** [tuiafceiaunr/fdcd#4]
Cada unidad tendrá: apunte, slides, práctica. La TOC debería verse así:
```
  - caption: Nombre de la unidad
    numbered: True
    chapters:
      - file: unidades/u1-nombre-unidad/apunte-unidad.md
      - file: unidades/u1-nombre-unidad/apunte-slides.md
      - file: unidades/u1-nombre-unidad/práctica.md
```

El archivo md de las slides tendrá algún título y el link a la slide.
