### ISSUE TITLE
Incluir todos todos los apuntes de práctica

### ISSUE THREAD

**Issue by msoltadeo** [tuiafceiaunr/fdcd#7]
@LucianoAD @laradc ya deployé el book, lo pueden ver [acá](https://tuiafceiaunr.github.io/fdcd/README.html). 
Lo que necesitaríamos ahora es que suban las prácticas de cada unidad. Para eso tienen que:
1. `git clone` este repositorio
2. Poner la práctica en markdown. Si van a usar las prácticas pasadas que están en notion, solo tienen que descargarlas de ahí. 
3. Generar un nuevo branch. 
4. Ubicar el archivo de markdown en la carpeta de cada unidas. Por ejemplo para la unidad 1 es [está](https://github.com/tuiafceiaunr/fdcd/tree/main/unidades/u1-planilla-calculo)
5. Actualizar la tabla de contenido [acá](https://github.com/tuiafceiaunr/fdcd/blob/main/docs/_toc.yml). Por ejemplo, para la unidad 1 quedaría algo así:
```
parts:
  - caption: Planilla de cálculo
    chapters:
      - file: unidades/u1-planilla-calculo/unidad-1-planilla-calculo.md
      - file: unidades/u1-planilla-calculo/unidad-1-planilla-calculo-practica.md
```
6. Comitear todos los archivos que cambiaron. NO olvidarse de la toc (yo me la olvido siempre 😢 )
7. Pushear el branch.
8. Mergear a Main.
9. Ir a Actions, [acá](https://github.com/tuiafceiaunr/fdcd/actions). Cuando hagan el merge se va a dispara un trabajo que va a deployar nuestro repo en github pages. Pueden seguir el proceso del trabajo desde el link que les pasé. Cuando esté en verde quiere decir que terminó. Si entran ahí, van a encontrar el link de la web.
